name: Go Quality Checks

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - name: go-vet
        run: go vet ./...
      - name: go-fmt
        run: FMT=`go fmt ./...` && [ -z "$FMT" ]
      - name: install-golint
        run: sudo apt update && sudo apt install -y golint
      - name: golint
        run: LINT=`golint ./...` && [ -z "$LINT" ]
